---
name: ((deployment_name))

instance_groups:
- instances: 1
  name: cf-redis-broker
  azs: [((default_az))]
  networks:
  - name: ((default_network))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk_type: ((default_persistent_disk_type))
  properties:
    route_registrar:
      routes:
      - health_check:
          name: ((broker_name))
          script_path: /var/vcap/jobs/cf-redis-broker/bin/health_check.sh
        name: broker_0
        port: 12350
        registration_interval: 10s
        tags:
          component: redis-broker
          env: production
        uris:
        - ((broker_name)).((system_domain))
  jobs:
  - name: cf-redis-broker
    release: cf-redis
    properties:
      broker:
        host: ((broker_name)).((system_domain))
        name: ((broker_name))
        username: ((broker_username))
        password: ((broker_password))
      cf:
        apps_domain: ((apps_domain))
        system_domain: ((system_domain))
      redis:       
        config_command: configalias
        maxmemory: 262144000
        save_command: anotherrandomstring
        bg_save_command: yetanotherrandomstring
        broker:
          name: ((broker_name))
          network: ((default_network))
          auth:
            username: ((broker_username))
            password: ((broker_password))
          service_id: ((service_id))
          service_instance_limit: 5
          service_name: ((service_name))
          shared_vm_plan_id: ((shared_vm_plan_id))
  - name: cf-cli-6-linux
    release: cf-cli
  - name: route_registrar
    release: routing
    consumes:
      nats: {from: nats, deployment: "((cf_deployment_name))"}
  - name: bpm
    release: bpm
  - name: syslog_forwarder
    release: syslog
    properties: &syslog-configuration
      syslog:
        address: ((syslog_endpoint_host))
        port: ((syslog_endpoint_port))
        transport: tcp
  - name: broker-registrar
    release: cf-redis
    properties:
      broker:
        name: ((broker_name))
        username: ((broker_username))
        password: ((broker_password))
      cf:
        api_url: https://api.((system_domain))
        admin_username: ((cf_username))
        admin_password: ((cf_password))
      redis:
        broker:
          service_instance_limit: 5
  - name: broker-deregistrar
    release: cf-redis
    properties:
      broker:
        name: ((broker_name))
      cf:
        api_url: https://api.((system_domain))
        admin_username: ((cf_username))
        admin_password: ((cf_password))
      redis:
        broker:
          service_instance_limit: 5
  - name: smoke-tests
    release: cf-redis
    properties:
      cf:
        api_url: https://api.((system_domain))
        apps_doimain: ((apps_domain))
        system_domain: ((system_domain))
        admin_username: ((cf_username))
        admin_password: ((cf_password))
      redis:
        broker:
          service_instance_limit: 5
      retry:
        backoff: linear
        baseline_interval_milliseconds: 1000
        max_attempts: 10

releases:
- name: cf-redis
  version: latest
- name: routing
  version: ((routing_version))
- name: bpm
  version: ((bpm_version))
- name: syslog
  version: ((syslog_version))
- name: cf-cli
  version: latest

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

update:
  canaries: 1
  canary_watch_time: 30000-180000
  max_in_flight: 6
  update_watch_time: 30000-180000
